services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql_air_checker
    environment:
      - MYSQL_DATABASE=airchecker
      - MYSQL_ROOT_PASSWORD=P@ssw0rd!
    ports:
      - "3306:3306"
    volumes:
      - ./airchecker/mysqldata:/var/lib/mysql
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - node-network

  emqx:
    image: emqx/emqx:5.3.0
    restart: unless-stopped
    container_name: emqx_air_checker
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    networks:
      - node-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: api
    ports:
      - "8080:80"
    networks:
      - node-network

  prediction_service:
    build:
      context: ./prediction-service
      dockerfile: Dockerfile
    restart: always
    container_name: prediction_service
    command: gunicorn -w 1 -b 0.0.0.0:8081 app:app
    ports:
      - "8081:8081"
    networks:
      - node-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client:/app/client
      - ./ssl:/ssl
    networks:
      - node-network

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: dashboard_air_checker
    ports:
      - "3002:3002"
    networks:
      - node-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_air_checker
    ports:
      - "9000:9000"
    volumes:
      - ./airchecker/portainerdata:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - node-network

  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./airchecker/mongodata:/data/db
    networks:
      - node-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana_air_checker
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=debug
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=viewer
      - GF_AUTH_DISABLE_LOGIN_FORM=tru
    ports:
      - "9001:3000"
    volumes:
      - ./airchecker/grafana-storage:/var/lib/grafana

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq_air_checker
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./airchecker/rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
