services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql_air_checker
    environment:
      - MYSQL_DATABASE=airchecker
      - MYSQL_ROOT_PASSWORD=P@ssw0rd!
    ports:
      - "3306:3306"
    volumes:
      - ./airchecker/mysqldata:/var/lib/mysql
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - node-network

  emqx:
    image: emqx/emqx:5.3.0
    restart: unless-stopped
    container_name: emqx_air_checker
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
